---
layout: cv
title: "Joshua Wells Resume"
---

## Contact Information
 
LinkedIn: [www.linkedin.com/in/joshua-wells-a9a514295](https://www.linkedin.com/in/joshua-wells-a9a514295)

## Relevant Experience

**Data Intern**  
*May 2024 - Present*  
*Idaho Falls Zoo at Tautphaus Park - Idaho Falls, ID*  
- Collaborating with two interns and Zoo employees to facilitate the Advancing Conservation through Empathy (ACE) project  
- Designed and updated project surveys using ARCGIS Survey123 platform  
- Ensured consistency in data collection for five published surveys  
- Analyzed data collected via ARCGIS to compare changes in public empathy over multiple years  
- Conducted statistical tests such as Independent Samples T-test and ANOVA F-test  

**Math Tutor**  
*Sep 2022 - Apr 2023*  
*BYU-Idaho Math Tutoring Center - Rexburg, ID*  
- Completed 20-25 hours of training across various mathematics topics  
- Encouraged growth mindset in dozens of students  
- Collaborated with two faculty members in the math department to ensure quality and accuracy in assisting with a broad range of math subjects  
- Provided private tutoring to two students in Rexburg and surrounding areas  

**Statistics Student**  
- Designed and conducted four experiments using BF[1], BF[2], CB[1], and SP/RM[1,1] statistical models  
- Consulted with Belnap Orthodontics to improve data-driven patient scheduling  

**Bioinformatics Course**  
- Conducted analysis on public scRNA-sequence data to visualize differential gene expression in patients with Aplastic Anemia  

**Programming Student**  
- Designed and implemented a program to read and handle `.pdb` files, calculating and displaying the mass and length of protein chains  

**Biochemistry Techniques Lab**  
- Explored differences in protein content of milk between four mammalian species  

## Education

**Bachelor's of Science in Biology** (minor in Statistics)  
*BYU-Idaho*  
*Sep 2019 - Jul 2025*  
- GPA: 3.95  
- R coding language  
- Python  
- MySQL  
- Object-Oriented Programming  
- PCR  
- Gel electrophoresis  
- Protein quantification assays  
- Protein purification  
- Gene cloning  

## Relevant Courses

- Biochemistry Lab Techniques  
- Bioinformatics  
- Experimental Design/ANOVA  
- Programming with Classes  

## Volunteer Experience

- Red Cross Blood Drives  
- BYU-Idaho Student Activities Volunteer  
- BYU-Idaho Pre-Optometry Society Presidency




<!-- ### Footer

Last updated: October 5, 2024 -->